- name: Install nginx package
  ansible.builtin.apt:
    name: nginx

- name: Configure nginx as a uWSGI frontend
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

#Install nginx-exporter
- name: Install prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Nginx-exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true