- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy

- name: Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart Haproxy

- name: Haproxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Install prometheus-haproxy-exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Configure prometheus-haproxy-exporter
  ansible.builtin.copy:
    src: prometheus-haproxy-exporter
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart prometheus-haproxy-exporter

- name: Prometheus-haproxy-exporter service
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Create DNS CNAME record for HAproxy servers
  community.general.nsupdate:
    server: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate."
    key_secret: "{{ nsupdate_key }}"
    type: "CNAME"
    zone: "{{ startup_domain }}"
    record: "lb-{{ inventory_hostname[-1] }}"
    value: "{{ inventory_hostname }}"
  loop: "{{ groups['dns_primary'] }}"

