- name: Pre-create necessary repositories
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources

- name: Add grafana.ini file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    owner: 472
    mode: '777'
  notify: Restart Grafana

- name: Add Grafana datasources
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}"
  loop:
    - prometheus.yaml
    - loki.yaml
  notify: Restart Grafana

- name: Add Grafana dashboards
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  loop:
    - dashboards.yaml
    - main.json
    - agamalog.json
    - backups.json
    - mysql.json
  notify: Restart Grafana

- name: Install Grafana (as container)
  community.docker.docker_container:
    image: grafana/grafana
    name: grafana
    volumes: /opt/grafana:/etc/grafana
    state: started
    published_ports: "{{ grafana_port }}:3000"
    log_driver: grafana/loki-docker-driver
    log_options:
      loki-url: http://jevgeni-arefjev-1:3100/loki/api/v1/push

- name: Create DNS CNAME record for Grafana server
  community.general.nsupdate:
    server: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate."
    key_secret: "{{ nsupdate_key }}"
    type: "CNAME"
    zone: "{{ startup_domain }}"
    record: "grafana"
    value: "{{ inventory_hostname }}"
  loop: "{{ groups['dns_primary'] }}"
