- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Create repository /etc/uwsgi/apps-enabled
  ansible.builtin.file:
    path: /etc/uwsgi/apps-enabled
    state: directory

- name: Add uWSGI app Agama configuration
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '400'
  no_log: true
  notify: Restart uWSGI

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

- name: Allow group adm to read agama log
  ansible.builtin.file:
    path: /var/log/uwsgi #cannot specify agama.log directly, because file does not exist at this moment.
    group: adm
    mode: '640'
