- name: Create directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Install agama app
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/main/{{ item }}"
    dest: "/opt/agama/{{ item }}"
  loop:
    - agama.py
    - Dockerfile

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Agama
  community.docker.docker_container:
    image: agama
    name: "agama-{{ item }}"
    state: started
    restart_policy: always 
    env:
      "AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    published_ports: "{{ agama_port + item }}:8000"
    log_driver: grafana/loki-docker-driver
    log_options:
      loki-url: http://loki:3100/loki/api/v1/push
  loop: "{{ range(1, num_agama_containers+1) | list }}"

- name: Create DNS CNAME record for Agama servers
  community.general.nsupdate:
    server: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate."
    key_secret: "{{ nsupdate_key }}"
    type: "CNAME"
    zone: "{{ startup_domain }}"
    record: "www-{{ inventory_hostname[-1] }}"
    value: "{{ inventory_hostname }}"
  loop: "{{ groups['dns_primary'] }}"

