- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    policy_rc_d: 101

- name: Configure MySQL to listen on public port
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Install pymysql
  ansible.builtin.apt:
    name: python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: MySQL user agama
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
  no_log: yes

# Installing prometheus exporter
- name: Install mysqld_exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    policy_rc_d: 101  #service will not start on installation

- name: Create MySQL user for mysqld_exporter
  community.mysql.mysql_user:
    name: "{{ mysqld_exporter_user }}"
    password: "{{ mysqld_exporter_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "localhost"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    #priv: "*.*:ALL"
  no_log: yes
  notify: Restart Prometheus-mysqld-exporter

- name: Create Prometheus/.my.cnf
  ansible.builtin.template:
    src: my.cnf_prometheus.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: '400'
    owner: prometheus
  no_log: yes
  notify: Restart Prometheus-mysqld-exporter

- name: Create prometheus_mysqld_exporter *ARGS
  ansible.builtin.copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart Prometheus-mysqld-exporter

- name: mysqld-exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: Create backup folder for MySQL
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '700'

- name: Create MySQL user for backup
  community.mysql.mysql_user:
    name: "{{ backup_mysql_user }}"
    password: "{{ backup_mysql_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "localhost"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
  no_log: yes
  notify: Restart Prometheus-mysqld-exporter

- name: Create backup/.my.cnf
  ansible.builtin.template:
    src: my.cnf_backup.j2
    dest: /home/backup/.my.cnf
    mode: '400'
    owner: backup
  no_log: yes

- name: Add cron backuping schedule
  ansible.builtin.template:
    src: backup-cron.j2
    dest: /etc/cron.d/mysql-backup

- name: MySQL user replication
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
  no_log: yes

- name: Set replica server to read-only
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: persist
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: Create DNS CNAME record for MySQL servers
  community.general.nsupdate:
    server: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate."
    key_secret: "{{ nsupdate_key }}"
    type: "CNAME"
    zone: "{{ startup_domain }}"
    record: "db-{{ inventory_hostname[-1] }}"
    value: "{{ inventory_hostname }}"
  loop: "{{ groups['dns_primary'] }}"
