server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: syslog-host
    static_configs:
    - targets:
        - localhost
      labels:
        job: syslog-host
        __path__: /var/log/syslog

  - job_name: agama
    static_configs:
    - targets:
       - localhost
      labels:
        job: agama
        __path__: /var/log/uwsgi/app/agama.log

  - job_name: nginx_access
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx_access
        __path__: /var/log/nginx/access.log

  - job_name: nginx_agama_log
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx_agama_log
        __path__: /var/log/nginx/agama.log

  - job_name: nginx_error
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx_error
        __path__: /var/log/nginx/error.log

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:514
      labels:
        job: "syslog"
