#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: change DNS resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

#- name: Prevent services from auto-starting
#  ansible.builtin.copy:
#    dest: /usr/sbin/policy-rc.d
#    content: |
#     #!/bin/sh
#      exit 101

- name: install prometheus node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

#- name: Add use juri
#  ansible.builtin.user:
#    name: juri
#    create_home: yes

#- name: Add user roman
#  ansible.builtin.user:
#    name: roman
#    create_home: yes

#- name: Set authorized keys for juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized keys for roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

